### ISSUE TITLE
V3 - Automation

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/pazusoba#10]
# TODO
- [ ] Detect board when it is complete blacked out
   - Go to every orb and hold until it is read
- [ ] Detect whether orbs are interactable
   - Detect battle (battle xx / xx) and wait for 1.5s
   - Detect empty tiles and wait for 1.5s or 3 cycles
   - When more than half the board is not readable (try again)
- [ ] Support more orbs
- [x] Support different game ratio (need more testing)
   - Currently, only 2:1 is supported
   - There are 16:9 and also 3:2 available
   - The new iPad UI is also different
   - Template should be the same but not sure if it matters
- [ ] Mac OS uses retina and the point location can be a bit different
- [x] Enter dungeons automatically
   - Pick the right dungeon
   - Choose my own leader
   - Enter the dungeon
- [x] Battle counter
   - Count battle from 0
   - Detect boss battle
   - Detect OK button (clear or game over)
- [ ] Stop when out of stamina 
- [x] Quit dungeon and avoid using magic stones
   - Still need to make sure touches are working
- [ ] Fix touch issues with pyautogui
   - Sometimes, it doesn't click or mouse down
- [ ] Use skill 1 to 6 (for 周回)
- [ ] Detect board location
   - This is important when porting to Android
   - Can use the heart icon to determine the location
- [x] Faster [screenshot](https://stackoverflow.com/questions/48144210/speeding-up-pyautogui-screenshot-with-region)
- [x] ~~~無限回廊三回まわる~~~
   - Pick the dungeon
   - Choose my own leader
   - Enter the dungeon
   - Count battle from 0 to 50
   - Clear the dungeon
   - Quit the dungeon
   - Do this 3 times
- [X] Normal dungeons
   - The program is running for a few hours and has cleared many normal dungeons one by one
- [ ] Battle detector not working all the time
   - This should be the first thing to check
   - Continue can be very dangerous sometimes

**Comment by HenryQuan** [comment]
This will be moved soon.
